// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy0jq-bzm2ZsXnumUEOvIczKCQG8kVdpk',
    appId: '1:995541774463:web:b798127e7fd582f9568f4a',
    messagingSenderId: '995541774463',
    projectId: 'vecinapp-2',
    authDomain: 'vecinapp-2.firebaseapp.com',
    storageBucket: 'vecinapp-2.appspot.com',
    measurementId: 'G-TX00ZYF1KM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvs5NZX-xLkU1U2MTQeosyKoJ55uGP-U0',
    appId: '1:995541774463:android:425840cedf64b782568f4a',
    messagingSenderId: '995541774463',
    projectId: 'vecinapp-2',
    storageBucket: 'vecinapp-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1CnJwpL6HjVGtFFDmhCorjNAQ1BBr1sE',
    appId: '1:995541774463:ios:817fc06d19bd43d8568f4a',
    messagingSenderId: '995541774463',
    projectId: 'vecinapp-2',
    storageBucket: 'vecinapp-2.appspot.com',
    iosClientId: '995541774463-uvlh1e2dts0t5f0a2s542hev1fmb3ra7.apps.googleusercontent.com',
    iosBundleId: 'com.cooperos.vecinapp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1CnJwpL6HjVGtFFDmhCorjNAQ1BBr1sE',
    appId: '1:995541774463:ios:8c6a3674e5d2b397568f4a',
    messagingSenderId: '995541774463',
    projectId: 'vecinapp-2',
    storageBucket: 'vecinapp-2.appspot.com',
    iosClientId: '995541774463-9tn3tah33nglvdeg9cii2o99uhbjjqpl.apps.googleusercontent.com',
    iosBundleId: 'com.cooperos.vecinapp2.RunnerTests',
  );
}
